function _(str)
{if((typeof Lang!='undefined')&&Lang[str])
return Lang[str];else
return str;}
var NextUp=(function(){var appForm=$('<form id="nextup-form" onsubmit="return false;"></form>');var formMeetingName=$('<input id="meeting-name" type="text" value="'+_('Name Your Meeting')+'"/>');var formMeetingTopics=$('<ol id="meeting-topics"></ol>');var formNewRow=$('<li></li>');var formNewTopic=$('<input type="text" class="topic" value="'+_('Topic')+'" onfocus="NextUp.focus(\''+_('Topic')+'\',this)" onblur="NextUp.blur(\''+_('Topic')+'\',this)"/>');var formNewTime=$('<input type="text" class="time" value="'+_('Time')+'" onfocus="NextUp.focus(\''+_('Time')+'\',this,\''+_('mm:ss')+'\')" onblur="NextUp.blur(\''+_('Time')+'\',this)"/>');var formActions=$('<div id="form-actions"></div>');var formAddTopic=$('<button id="add-topic">'+_('Add Another Topic')+'</button>');var formCreateMeeting=$('<button id="create-meeting">'+_('Create Agenda')+'</button>');var formTooltip=$('<div id="form-tooltip"><span></span></div>').hide();$(formNewRow).append(formNewTopic).append(formNewTime);$(formActions).append(formAddTopic).append(formCreateMeeting);$(appForm).append(formMeetingName).append(formMeetingTopics).append(formActions).append(formTooltip);$(formMeetingName).focus(function(){NextUp.focus.call(this,_('Name Your Meeting'));}).blur(function(){NextUp.blur.call(this,_('Name Your Meeting'));});var appCountdown=$('<div id="meeting"></div>');var agendaTitle=$('<h2></h2>');var agendaActions=$('<div id="agenda-actions"></div>');var agendaStart=$('<button id="start-meeting">'+_('Start The Meeting')+'</button>');var agendaList=$('<ol id="agenda-items"></ol>');var agendaItem=$('<li></li>');var agendaTopic=$('<span class="topic"></span>');var agendaTime=$('<span class="time"></span>');$(agendaActions).append(agendaStart);var regexTimeShort=/^(\d+)\s+(s|m|h)$/i;function addAgendaItem(topic,time){$(agendaList).append($(agendaItem).clone().append($(agendaTopic).clone().text(topic)).append($(agendaTime).clone().text(time)));}
$(agendaStart).click(function(){NextUp.startMeeting();});$(appCountdown).append(agendaTitle).append(agendaActions).append(agendaList);function timeToSeconds(time){var t=time.split(':');var seconds=0;switch(t.length){case 3:seconds=3600*t[0]+60*t[1]+parseInt(t[2],10);break;case 2:seconds=60*t[0]+parseInt(t[1],10);break;case 1:default:seconds=parseInt(t[0],10);}
return seconds;}
function secondsToTime(seconds){var time;var s=seconds%60;minutes=(seconds-s)/60;if(minutes>60){var m=minutes%60;var hours=(minutes-m)/60;}else{var m=minutes;}
if(hours){if(s<10)s='0'+String(s);if(m<10)m='0'+String(m);return hours+':'+m+':'+s;}else if(m){if(s<10)s='0'+String(s);return m+':'+s;}else{return s;}}
var counter;function countdown(){var all=$('#agenda-items li');if(0==$(all).length){clearInterval(counter);NextUp.endOfMeeting();return;}
var current=all[0];$(current).toggleClass('active',true);var time=$(current).children('.time')[0];var left=timeToSeconds($(time).text())-1;$(time).text(secondsToTime(left));if(0==left){$(current).fadeOut(900,function(){var t=$('#agenda-items li:first-child');if($(t).is(':hidden')){$(t).remove()}});}
if(left<15){$(current).toggleClass('less-than-15',true);$(current).toggleClass('less-than-60',false);}else if(left<60){$(current).toggleClass('less-than-60',true);}}
return{helpEnabled:true,addTopic:function(){$(formMeetingTopics).append(formNewRow.clone());return this;},focus:function(def,obj,msg){var target=obj||this;if(def==target.value){target.value='';}
target.style.color='#444';if(NextUp.helpEnabled&&msg){var _top=$(target).offset().top+1;var _left=$(target).offset().left+$(target).outerWidth()+5;$(formTooltip).css({top:_top+'px',left:_left+'px'}).show().children('span').text(msg);}},blur:function(def,obj){var target=obj||this;if(''==target.value||def==target.value){target.style.color='#cbdf90';target.value=def;}
$(formTooltip).hide();},createMeeting:function(){var meetingTitle=$('#meeting-name').attr('value');if(_('Name Your Meeting')==meetingTitle||''==meetingTitle)meetingTitle=_('Agenda');document.title=meetingTitle+' - '+document.title;$(agendaTitle).text(meetingTitle);$('#meeting-topics li').each(function(){var topic=$(this).children('.topic').attr('value');var time=$(this).children('.time').attr('value');if((_('Topic')!=topic&&''!=topic)&&(_('Time')!=time&&''!=time)){addAgendaItem(topic,time);}});$('#nextup-app').empty().append(appCountdown);},startMeeting:function(){$('#agenda-items li:first-child').toggleClass('active',true);$('#agenda-actions').remove();counter=setInterval(countdown,1000);},endOfMeeting:function(){var overText=$('<h2>'+_('Meeting\'s Over!')+'</h2>');var overAction=$('<div id="over-actions"></div>');var overReload=$('<button id="over-reload">'+_('Start Again?')+'</button>').click(function(){window.location.reload(true);});$(overAction).append(overReload);$("#nextup-app").append(overText).append(overAction);},load:function(){$(formMeetingTopics).append(formNewRow.clone()).append(formNewRow.clone());$(formAddTopic).click(NextUp.addTopic);$(formCreateMeeting).click(NextUp.createMeeting);$('#nextup-app').empty().append(appForm);}}})();$(document).ready(NextUp.load);
